logging:
  level: INFO
  appenders:
    - type: console

# Database settings.
database:
  driverClass: org.h2.Driver
  user: root
  password: password
  url: jdbc:h2:./users.db

auth:
  secret: secret
  
